service: sam

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements: # permissions for all of your functions can be set here
  - Effect: Allow
    Action: # Gives permission to DynamoDB tables in a specific region
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: "arn:aws:dynamodb:ap-northeast-1:*:*"

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  cameraGet:
    handler: bin/cameraGet
    events:
      - http:
          path: camera/{mac}
          method: get
  cameraPost:
    handler: bin/cameraPost
    events:
      - http:
          path: camera
          method: post
  monitorGet:
    handler: bin/monitorGet
    events:
      - http:
          path: monitor
          method: get

resources:
  Resources:
    camera:
      Type: "AWS::DynamoDB::Table"

      Properties:
        AttributeDefinitions:
          -
            AttributeName: "mac"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "mac"
            KeyType: "HASH"

        ProvisionedThroughput:
          ReadCapacityUnits: "1"
          WriteCapacityUnits: "1"
        TableName: "camera"